spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tp2
        username: root
        password: admin
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    mail:
        host: smtp.gmail.com
        username: leyva.calle1403@gmail.com
        password: zxfjbrchgptmsblb
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
